name = "UpdatableQRFactorizations"
uuid = "8b110c62-ada2-4dd7-b53a-29f29fe8f7f4"
authors = ["Sebastian Ament <sebastianeament@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
